'use client';

import { Printer, ArrowLeft, Building2 } from 'lucide-react';
import NextLink from 'next/link';
import { Button } from '@/components/ui/button';

export default function ImpactReportView({ data }: { data: any }) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 print:bg-white print:text-black">
      {/* Non-printable header */}
      <div className="print:hidden bg-slate-900 text-white p-4 flex justify-between items-center sticky top-0 z-10 shadow-md">
        <NextLink href="/official" className="flex items-center gap-2 hover:text-blue-400 transition-colors">
          <ArrowLeft size={20} /> Back to Dashboard
        </NextLink>
        <Button onClick={handlePrint} className="bg-blue-600 hover:bg-blue-700 text-white gap-2">
          <Printer size={18} /> Download as PDF
        </Button>
      </div>

      {/* Printable Report Content */}
      <div className="max-w-4xl mx-auto p-8 print:p-0 bg-white shadow-xl my-8 print:my-0 print:shadow-none min-h-[1056px]">
        {/* Report Header */}
        <div className="border-b-4 border-slate-900 pb-6 mb-8 flex justify-between items-end">
          <div>
            <div className="flex items-center gap-3 text-slate-900 mb-2">
              <Building2 size={32} />
              <h1 className="text-3xl font-serif font-bold tracking-tight">Municipal Impact Report</h1>
            </div>
            <p className="text-slate-600 font-medium text-lg">City of {data.city || 'Metropolis'}</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Generated By</p>
            <p className="font-semibold">{data.officialName}</p>
            <p className="text-sm text-slate-500">{new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
        </div>

        {/* Executive Summary (AI Generated) */}
        <div className="mb-10">
          <h2 className="text-xl font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">Executive Summary</h2>
          <div className="bg-slate-50 border-l-4 border-blue-600 p-6 rounded-r-xl">
            <p className="text-lg leading-relaxed text-slate-700 serif">
              {data.narrative}
            </p>
          </div>
        </div>

        {/* Key Metrics */}
        <div className="mb-10">
          <h2 className="text-xl font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">Key Performance Metrics</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="border border-slate-200 rounded-xl p-5 text-center bg-slate-50">
              <p className="text-4xl font-bold text-slate-900 mb-1">{data.total}</p>
              <p className="text-xs uppercase font-bold tracking-wider text-slate-500">Total Reports</p>
            </div>
            <div className="border border-slate-200 rounded-xl p-5 text-center bg-green-50">
              <p className="text-4xl font-bold text-green-700 mb-1">{data.resolved}</p>
              <p className="text-xs uppercase font-bold tracking-wider text-green-600">Resolved</p>
            </div>
            <div className="border border-slate-200 rounded-xl p-5 text-center bg-purple-50">
              <p className="text-4xl font-bold text-purple-700 mb-1">{data.duplicates}</p>
              <p className="text-xs uppercase font-bold tracking-wider text-purple-600">Duplicates Avoided</p>
            </div>
            <div className="border border-slate-200 rounded-xl p-5 text-center bg-red-50">
              <p className="text-4xl font-bold text-red-700 mb-1">{data.emergency}</p>
              <p className="text-xs uppercase font-bold tracking-wider text-red-600">Emergencies Handled</p>
            </div>
          </div>
        </div>

        {/* Efficiency Calculation */}
        <div className="mb-10">
          <h2 className="text-xl font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">Resource Efficiency</h2>
          <table className="w-full text-left border-collapse">
            <tbody>
              <tr className="border-b border-slate-100">
                <td className="py-3 font-medium text-slate-600">Estimated Manual Triage Time Saved</td>
                <td className="py-3 font-bold text-right text-slate-900">{Math.round(data.total * 0.25)} hours</td>
              </tr>
              <tr className="border-b border-slate-100">
                <td className="py-3 font-medium text-slate-600">Estimated Duplicate Labor Prevented</td>
                <td className="py-3 font-bold text-right text-slate-900">{Math.round(data.duplicates * 4.5)} hours</td>
              </tr>
              <tr className="bg-slate-50">
                <td className="py-4 px-3 font-bold text-lg text-slate-800">Total Labor Hours Reclaimed</td>
                <td className="py-4 px-3 font-bold text-xl text-right text-blue-700">
                  {Math.round((data.total * 0.25) + (data.duplicates * 4.5))} hrs
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Category Breakdown */}
        <div>
          <h2 className="text-xl font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">Issue Breakdown</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {Object.entries(data.categories).map(([category, count]) => (
              <div key={category} className="flex justify-between items-center border-b border-slate-100 py-2">
                <span className="font-medium text-slate-700">{category}</span>
                <span className="font-bold bg-slate-100 px-3 py-1 rounded-full text-sm">{String(count)}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-16 pt-6 border-t border-slate-200 text-center text-sm text-slate-400">
          <p>This report was generated automatically by CivicTriage AI.</p>
          <p className="mt-1">For questions, contact the Department of Civic Innovation.</p>
        </div>
      </div>
    </div>
  );
}
